In [44]:
import pandas as pd
import glob

In [45]:
folder_path = "CSV files/*.csv"
all_files = glob.glob(folder_path)
df_list = [pd.read_csv(filename) for filename in all_files]
df = pd.concat(df_list, ignore_index=True)

In [46]:
df.head()

,,Time,Time.1,Place,Place.1,Place.2,Place.3,Place.4,Place.5,Place.6,...,Events.4,Events.5,Assessments,Assessments.1,Report 1,Report 1.1,Report 2,Report 2.1,Report 1.2,Unnamed: 125
0,ACN,Date,Local Time Of Day,Locale Reference,State Reference,Relative Position.Angle.Radial,Relative Position.Distance.Nautical Miles,Altitude.AGL.Single Value,Altitude.MSL.Single Value,Latitude / Longitude (UAS),...,When Detected,Result,Contributing Factors / Situations,Primary Problem,Narrative,Callback,Narrative,Callback,Synopsis,NaN
1,1714400,202001,0001-0600,ORD.Airport,IL,NaN,NaN,NaN,15000,NaN,...,In-flight,Air Traffic Control Issued New Clearance; Air ...,Aircraft; Company Policy,Company Policy,To be clear I did not have a lot going on and ...,NaN,NaN,NaN,A TRACON Departure Controller reported two air...,NaN
2,1714553,202001,1801-2400,ZHU.ARTCC,TX,NaN,NaN,NaN,14000,NaN,...,In-flight,Flight Crew Became Reoriented; General Physica...,Human Factors; Environment - Non Weather Related,Environment - Non Weather Related,While descending into PIB out of 14;000 ft. MS...,NaN,NaN,NaN,CRJ Captain reported that a laser shone repeat...,NaN
3,1714675,202001,1801-2400,ZZZ.ARTCC,US,NaN,NaN,NaN,9000,NaN,...,In-flight,Flight Crew Returned To Departure Airport; Fli...,Aircraft; Weather; Procedure,Weather,I was boarding the aircraft when a my destinat...,NaN,NaN,NaN,Pilot reported weather and a closed destinatio...,NaN
4,1714708,202001,0601-1200,ZZZ.Airport,US,NaN,NaN,0,NaN,NaN,...,In-flight,General None Reported / Taken,Procedure; Logbook Entry; Human Factors,Ambiguous,I had a ferry flight that went out of service ...,NaN,We departed ZZZ ferrying an un-airworthy aircr...,NaN,Air carrier Dispatcher and flight crew reporte...,NaN

In [47]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 31141 entries, 0 to 31140
Columns: 126 entries,   to Unnamed: 125
dtypes: float64(1), str(125)
memory usage: 29.9 MB

In [48]:
df_1 = df.copy()

In [49]:
df_1 = df_1[['Events','Report 1']]

In [50]:
df_1.head()

,Events,Report 1
0,Anomaly,Narrative
1,ATC Issue All Types; Conflict Airborne Conflic...,To be clear I did not have a lot going on and ...
2,Flight Deck / Cabin / Aircraft Event Illness /...,While descending into PIB out of 14;000 ft. MS...
3,Aircraft Equipment Problem Less Severe; Deviat...,I was boarding the aircraft when a my destinat...
4,Aircraft Equipment Problem Less Severe; Deviat...,I had a ferry flight that went out of service ...

In [51]:
df_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 31141 entries, 0 to 31140
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Events    31124 non-null  str
 1   Report 1  31138 non-null  str
dtypes: str(2)
memory usage: 486.7 KB

In [52]:
df_1.isnull().sum()/len(df_1) * 100

Events      0.054590
Report 1    0.009634
dtype: float64

In [53]:
df_1.dropna(inplace = True)

In [54]:
df_1.info()

<class 'pandas.DataFrame'>
Index: 31124 entries, 0 to 31140
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Events    31124 non-null  str
 1   Report 1  31124 non-null  str
dtypes: str(2)
memory usage: 729.5 KB

In [55]:
df_1.isnull().sum()/len(df_1) * 100

Events      0.0
Report 1    0.0
dtype: float64

In [56]:
df_1.columns = df_1.iloc[0]
df_1 = df_1.drop(df.index[0])
df_1 = df_1.reset_index(drop=True)

In [60]:
df_1['Anomaly'].value_counts()

Anomaly
Aircraft Equipment Problem Critical                                                                                                                                                                                                                                             2539
Conflict NMAC                                                                                                                                                                                                                                                                   1064
Aircraft Equipment Problem Critical; Deviation / Discrepancy - Procedural Published Material / Policy                                                                                                                                                                            686
Conflict NMAC; Deviation / Discrepancy - Procedural Published Material / Policy                                                                                                                                                                                                  508
Aircraft Equipment Problem Less Severe                                                                                                                                                                                                                                           467
                                                                                                                                                                                                                                                                                ...
Deviation / Discrepancy - Procedural FAR; Deviation / Discrepancy - Procedural Published Material / Policy; Ground Event / Encounter Loss Of Aircraft Control; Ground Excursion Runway; Ground Incursion Runway                                                                    1
Aircraft Equipment Problem Critical; Deviation / Discrepancy - Procedural Published Material / Policy; Ground Event / Encounter Object; Ground Excursion Taxiway                                                                                                                   1
Deviation - Altitude Excursion From Assigned Altitude; Deviation - Altitude Overshoot; Deviation - Altitude Undershoot; Deviation / Discrepancy - Procedural Clearance; Inflight Event / Encounter Loss Of Aircraft Control; Inflight Event / Encounter Weather / Turbulence       1
Conflict NMAC; Inflight Event / Encounter Object; Inflight Event / Encounter Bird / Animal                                                                                                                                                                                         1
ATC Issue All Types; Deviation - Speed All Types; Deviation / Discrepancy - Procedural Published Material / Policy; Inflight Event / Encounter CFTT / CFIT                                                                                                                         1
Name: count, Length: 6407, dtype: int64